### ISSUE TITLE
Creating a file with a size of 300 MB while doing "Build"

### ISSUE THREAD

**Issue by MhmudAlpurd** [neso613/ASR_TFLite#2]
Hi Neha, you are amazing, thank you for this guide.I have a question about that, The output file (apk) of this code is very large due to creating a build folder (300MB) automatically, and this makes the file (apk) useless. is there any solution to solve this?

Thank you.

**Comment by neso613** [comment]
Thanks @MhmudAlpurd  for reporting this issue.
Will look into this forward and get back to you soon.
@windmaple Please share your thoughts on this?

**Comment by windmaple** [comment]
I already replied in [here](https://github.com/windmaple/tflite-asr/issues/1)

It's a combination of standard Android optimization and TFLite-specific optimization. I can't help much on the Android side, but for TFLite model, if you re-convert it w/ the latest build, we may not need Flex any more, which can reduce a few MBs.
